"""Export a trained residual model bundle into an ESP32 C++ header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


EXPECTED_FEATURE_COLUMNS = [
    "depth_err_cm",
    "depth_speed_cm_s",
    "depth_accel_cm_s2",
    "roll_deg",
    "pitch_deg",
    "gyro_x_deg_s",
    "gyro_y_deg_s",
    "gyro_z_deg_s",
    "battery_v",
    "buoyancy_pwm_applied",
]


def main() -> None:
    args = parse_args()
    payload = json.loads(Path(args.model).read_text(encoding="utf-8"))
    header_text = render_header(
        payload=payload,
        namespace=args.namespace,
        include_guard=args.include_guard,
    )
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header_text, encoding="utf-8")
    print(f"wrote ESP32 model header to {output_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a trained residual model JSON bundle as an ESP32 C++ header.",
    )
    parser.add_argument("--model", required=True, help="Path to residual_model.json")
    parser.add_argument("--output", required=True, help="Path to the generated .h file")
    parser.add_argument(
        "--namespace",
        default="residual_model",
        help="C++ namespace for the generated constants",
    )
    parser.add_argument(
        "--include-guard",
        default="ESP32_RESIDUAL_MODEL_DATA_H",
        help="Header include guard",
    )
    return parser.parse_args()


def render_header(
    *,
    payload: dict[str, object],
    namespace: str = "residual_model",
    include_guard: str = "ESP32_RESIDUAL_MODEL_DATA_H",
) -> str:
    metadata = payload["metadata"]
    input_standardizer = payload["input_standardizer"]
    target_standardizer = payload["target_standardizer"]
    model = payload["model"]

    if not isinstance(metadata, dict):
        raise ValueError("metadata must be a mapping")
    if not isinstance(input_standardizer, dict):
        raise ValueError("input_standardizer must be a mapping")
    if not isinstance(target_standardizer, dict):
        raise ValueError("target_standardizer must be a mapping")
    if not isinstance(model, dict):
        raise ValueError("model must be a mapping")

    window_size = int(metadata["window_size"])
    feature_columns = [str(value) for value in metadata["feature_columns"]]
    input_dim = int(model["input_dim"])
    hidden_dims = [int(value) for value in model["hidden_dims"]]
    layers = model["layers"]
    if not isinstance(layers, list) or len(hidden_dims) != 2 or len(layers) != 3:
        raise ValueError("export currently supports exactly two hidden layers")
    if window_size < 1:
        raise ValueError("window_size must be positive")

    base_feature_count = len(feature_columns)
    if base_feature_count * window_size != input_dim:
        raise ValueError("window_size * base_feature_count must match input_dim")
    if feature_columns != EXPECTED_FEATURE_COLUMNS:
        raise ValueError(
            "feature_columns must match the ESP32 inference contract exactly: "
            + ", ".join(EXPECTED_FEATURE_COLUMNS)
        )

    means = [float(value) for value in input_standardizer["means"]]
    stds = [float(value) for value in input_standardizer["stds"]]
    target_mean = float(target_standardizer["means"][0])
    target_std = float(target_standardizer["stds"][0])

    if len(means) != input_dim or len(stds) != input_dim:
        raise ValueError("input standardizer dimension does not match input_dim")

    layer0 = _read_layer(layers[0])
    layer1 = _read_layer(layers[1])
    layer2 = _read_layer(layers[2])

    lines = [
        f"#ifndef {include_guard}",
        f"#define {include_guard}",
        "",
        "// Auto-generated by learning/export_to_esp32.py.",
        "// Regenerate this file after retraining the residual controller.",
        "// Feature order: " + ", ".join(feature_columns),
        "",
        "#include <Arduino.h>",
        "",
        f"namespace {namespace} {{",
        "",
        "constexpr bool kModelAvailable = true;",
        f"constexpr uint8_t kWindowSize = {window_size};",
        f"constexpr uint8_t kBaseFeatureCount = {base_feature_count};",
        f"constexpr uint16_t kInputDim = {input_dim};",
        f"constexpr uint8_t kHidden1Size = {hidden_dims[0]};",
        f"constexpr uint8_t kHidden2Size = {hidden_dims[1]};",
        f"constexpr float kTargetMean = {_format_float(target_mean)};",
        f"constexpr float kTargetStd = {_format_float(target_std)};",
        "",
        _format_1d_array("kInputMeans", means),
        "",
        _format_1d_array("kInputStds", stds),
        "",
        _format_2d_array("kLayer0Weights", layer0["weights"]),
        "",
        _format_1d_array("kLayer0Biases", layer0["biases"]),
        "",
        _format_2d_array("kLayer1Weights", layer1["weights"]),
        "",
        _format_1d_array("kLayer1Biases", layer1["biases"]),
        "",
        _format_2d_array("kLayer2Weights", layer2["weights"]),
        "",
        _format_1d_array("kLayer2Biases", layer2["biases"]),
        "",
        "}  // namespace " + namespace,
        "",
        f"#endif  // {include_guard}",
        "",
    ]
    return "\n".join(lines)


def _read_layer(layer_payload: object) -> dict[str, list[list[float]] | list[float]]:
    if not isinstance(layer_payload, dict):
        raise ValueError("layer payload must be a mapping")

    weights = [[float(value) for value in row] for row in layer_payload["weights"]]
    biases = [float(value) for value in layer_payload["biases"]]
    return {"weights": weights, "biases": biases}


def _format_float(value: float) -> str:
    text = f"{value:.9f}".rstrip("0").rstrip(".")
    if "." not in text:
        text += ".0"
    return text + "f"


def _format_1d_array(name: str, values: list[float]) -> str:
    body = ", ".join(_format_float(value) for value in values)
    return f"constexpr float {name}[{len(values)}] = {{ {body} }};"


def _format_2d_array(name: str, rows: list[list[float]]) -> str:
    if not rows or not rows[0]:
        raise ValueError(f"{name} must not be empty")

    rendered_rows = []
    for row in rows:
        rendered_rows.append("    { " + ", ".join(_format_float(value) for value in row) + " }")
    return (
        f"constexpr float {name}[{len(rows)}][{len(rows[0])}] = {{\n"
        + ",\n".join(rendered_rows)
        + "\n};"
    )


if __name__ == "__main__":
    main()
